[keyboard]
name = "rmk-right"
product_name = "rmk-right"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
board = "pi_pico_w"
serial_number = "vial:f64c2b3c:000002"
# NOTE: usb_enable を true から false にするとビルド時にパニックする（no usb info for the chip）
usb_enable = true

[host]
#一時的に無効化
#vial_enabled = false

[storage]
#vialとsplitには必要
enabled = true
# Set `clear_storage` to true to clear all the stored info when the keyboard boots
# ペアリング情報を保持するため通常は false（初回リセット時だけ true）
clear_storage = true

[aliases]
# BLE profile keycodes are User0..User(N+3). Clear bond = User(N+2),
# where N = ble_profiles_num (default 3) in [rmk].
CLR_BT = "User5"

[matrix]
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
    ["PIN_6", "PIN_10", "PIN_11", "PIN_12", "PIN_7"],
    ["PIN_27", "PIN_15", "PIN_14", "PIN_8", "PIN_13"],
    ["PIN_18", "PIN_19", "PIN_20", "PIN_21", "PIN_9"],
    ["PIN_16", "PIN_17", "_", "_", "_"],
]

[layout]
rows = 4
cols = 5
layers = 3
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4)
(1,0) (1,1) (1,2) (1,3) (1,4)
(2,0) (2,1) (2,2) (2,3) (2,4)
(3,0) (3,1)
"""

[[layer]]
name = "base_layer"
keys = """
Y U I O P
H J K L Semicolon
N M Comma Dot Slash
LCtrl TO(1)
"""

[[layer]]
name = "layer2"
keys = """
F6  F7  F8         F9          F10
Kc6 Kc7 Kc8        Kc9         Kc0
Grave Quote LeftBracket RightBracket Backslash
LCtrl TO(2)
"""

[[layer]]
name = "layer3"
keys = """
@CLR_BT PageDown PageUp End Delete
Left Down Up Right Backspace
MouseWheelLeft MouseWheelDown MouseWheelUp MouseWheelRight Enter
LCtrl TO(0)
"""

[ble]
enabled = true
