[keyboard]
name = "rmk-left"
product_name = "rmk-left"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
board = "pi_pico_w"
serial_number = "vial:f64c2b3c:000001"
# NOTE: usb_enable を true から false にするとビルド時にパニックする（no usb info for the chip）
usb_enable = true

[host]
#一時的に無効化
#vial_enabled = false

[storage]
#vialとsplitには必要
enabled = true
# Set `clear_storage` to true to clear all the stored info when the keyboard boots
# ペアリング情報を保持するため通常は false（初回リセット時だけ true）
clear_storage = false

[aliases]
# BLE profile keycodes are User0..User(N+3). Clear bond = User(N+2),
# where N = ble_profiles_num (default 3) in [rmk].
CLR_BT = "User5"

[matrix]
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
    ["PIN_3", "PIN_12", "PIN_11", "PIN_10", "PIN_2"],
    ["PIN_13", "PIN_4", "PIN_14", "PIN_15", "PIN_27"],
    ["PIN_5", "PIN_21", "PIN_20", "PIN_19", "PIN_18"],
    ["_", "_", "_", "PIN_16", "PIN_17"],
]

[layout]
rows = 4
cols = 5
layers = 3
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4)
(1,0) (1,1) (1,2) (1,3) (1,4)
(2,0) (2,1) (2,2) (2,3) (2,4)
                  (3,3) (3,4)
"""

[[layer]]
name = "base_layer"
keys = """
Q W E R T
A S D F G
Z X C V B
      TO(2) LShift
"""

[[layer]]
name = "layer2"
keys = """
F1  F2  F3    F4    F5
Kc1 Kc2 Kc3   Kc4   Kc5
F11 F12 Minus Equal Space
      TO(0) LShift
"""

[[layer]]
name = "layer3"
keys = """
Escape MouseAccel0 MouseAccel1 MouseAccel2 @CLR_BT
Tab    MouseLeft   MouseDown   MouseUp     MouseRight
LAlt   LGui        MouseBtn1   MouseBtn3   MouseBtn2
      TO(1) LShift
"""

[ble]
enabled = true
