[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2350"
# runner = "elf2uf2-rs -d"

[build]
target = "thumbv8m.main-none-eabihf" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
KEYBOARD_TOML_PATH =  { value = "keyboard.toml", relative = true }
